language: node_js
node_js:
  - "0.10.33"

branches:
  only:
    - master

addons:
  postgresql: "9.3"

before_install:

  # Add a local loopback interface for IP 127.0.0.2
  - sudo ip addr add 127.0.0.2 dev lo

  # Create virtual hosts
  - sudo sed -i "2i127.0.0.2  2014.cam.timetable.grasshopper.com" /etc/hosts
  - sudo sed -i "2i127.0.0.2  2013.cam.timetable.grasshopper.com" /etc/hosts
  - sudo sed -i "2i127.0.0.1  admin.grasshopper.com" /etc/hosts
  - sudo cat /etc/hosts

  # Install test dependencies
  - npm install -g casperjs

  # Show the CasperJS and PhantomJS version for debugging purposes
  - casperjs --version
  - phantomjs --version

  # Prepare the machine
  - sudo apt-get update
  - sudo apt-get install build-essential
  - cd /usr/local/lib

  # Get Apache HTTP-server 2.4
  - sudo wget http://lib.gblearn.com/apache/httpd-2.4.10.tar.gz -q
  - sudo tar xfz httpd-2.4.10.tar.gz
  - cd httpd-2.4.10/srclib/

  # Download depencendies
  - sudo wget http://lib.gblearn.com/apache/apr/apr-1.5.1.tar.gz -q
  - sudo wget http://lib.gblearn.com/apache/apr/apr-util-1.5.3.tar.gz -q
  - sudo wget http://lib.gblearn.com/apache/pcre/pcre-8.34.tar.gz -q

  # Install and configure APR
  - echo 'Installing APR'
  - sudo tar xfz ./apr-1.5.1.tar.gz
  - cd apr-1.5.1
  - sudo ./configure
  - sudo make --silent
  - sudo make install --silent
  - cd ../

  # Install and configure APR util
  - echo 'Installing APR util'
  - sudo tar xfz ./apr-util-1.5.3.tar.gz
  - cd apr-util-1.5.3
  - sudo ./configure --with-apr=/usr/local/apr/bin/apr-1-config
  - sudo make --silent
  - sudo make install --silent
  - cd ../

  # Install and configure PCRE
  - echo 'Installing PCRE'
  - sudo tar xfz pcre-8.34.tar.gz
  - cd pcre-8.34
  - sudo ./configure --prefix=/usr/local/pcre
  - sudo make --silent
  - sudo make install --silent
  - cd ../..

  # Install and configure Apache HTTPD 2.4
  - echo 'Installing Apache'
  - sudo ./configure --prefix=/usr/local/apache2 --with-pcre=/usr/local/pcre --enable-so
  - sudo make --silent
  - sudo make install --silent
  - cd /usr/local/apache2/conf
  - sudo mkdir sites-enabled

  # Install Grasshopper
  - echo 'Installing Grasshopper'
  - cd ~/build/CUL-DigitalServices
  - git clone --branch master --depth=1 git://github.com/CUL-DigitalServices/grasshopper.git ./grasshopper
  - cd ./grasshopper
  - npm install --production

  # Configure postgres
  - echo 'Creating database'
  - psql -c 'create database grasshoppertest;' -U postgres
  - printf "\n\nconfig.db.username = 'postgres';" >> config.js

  # Install Grasshopper UI
  - echo 'Installing Grasshopper UI'
  - cd ~/build/CUL-DigitalServices/grasshopper-ui
  - npm install
  - grunt configApache
  - sudo cp ./target/optimized/apache/httpd.conf /usr/local/apache2/conf/httpd.conf
  - sudo cp -R ./target/optimized/apache/app_*.conf /usr/local/apache2/conf/sites-enabled

  # Start Apache
  - sudo /usr/local/apache2/bin/apachectl start
  - sleep 5

script:
  - grunt test

after_script:
  - grunt coveralls

after_success:
  # Package and upload to Amazon S3
  - ./etc/scripts/travis-upload.sh

notifications:
  email:
    - bp323@cam.ac.uk
    - md623@cam.ac.uk
  irc:
    channels:
      - "irc.freenode.org#ucam-ds"
    skip_join: true
